---
  AllCops:
    TargetRubyVersion: 2.4
  
  Style/FrozenStringLiteralComment:
    Enabled: false
    
  Style/SpecialGlobalVars:
    Enabled: false
  
  Metrics/ClassLength:
    Max: 200

  Metrics/MethodLength:
    Max: 20
  
  Metrics/AbcSize:
    Max: 20
  
  Lint/AssignmentInCondition:
    Enabled: false
  
  Metrics/BlockLength:
    Exclude:
      - 'app_archetype.gemspec'
      - 'spec/**/*'
