---
  AllCops:
    TargetRubyVersion: 2.6
  
  Style/FrozenStringLiteralComment:
    Enabled: false
    
  Style/SpecialGlobalVars:
    Enabled: false

  Style/MissingRespondToMissing:
    Enabled: false
  
  Metrics/ClassLength:
    Max: 200

  Metrics/MethodLength:
    Max: 20
    Exclude: 
      - 'lib/app_archetype/renderer.rb'
  
  Metrics/AbcSize:
    Max: 20
    Exclude: 
      - 'lib/app_archetype/renderer.rb'
  
  Metrics/CyclomaticComplexity:
    Exclude: 
      - 'lib/app_archetype/renderer.rb'

  Metrics/PerceivedComplexity:
    Exclude: 
      - 'lib/app_archetype/renderer.rb'
  
  Lint/AssignmentInCondition:
    Enabled: false
  
  Metrics/BlockLength:
    Exclude:
      - 'app_archetype.gemspec'
      - 'spec/**/*'

  Gemspec/RequiredRubyVersion:
    Enabled: false

  Style/IfUnlessModifier:
    Enabled: false

  Style/GlobalStdStream:
    Enabled: false

  Style/OptionalBooleanParameter:
    Enabled: false
