image: ruby:2.6.4

pipelines:
  branches:
    master:
      - step:
          name: Build and Test
          caches:
            - bundler
          script:
            - gem install bundler
            - bundle install --path .bundle
            - bundle exec rake
          deployment: production

definitions:
  caches:
    bundler: .bundle
