#!/usr/bin/env ruby

require 'thor'
require 'app_archetype'
require 'active_support/all'

puts 'CREATE NEW COMMAND'

template_dir = File.join(__dir__, 'generators')
manager = AppArchetype::TemplateManager.new(template_dir)
manager.load

manifest = manager.find_by_name('command')
template = manifest.template
template.load

manifest.variables.all.each do |var|
  value = AppArchetype::CLI::Prompts.variable_prompt_for(var)
  var.set!(value)
end

plan = AppArchetype::Template::Plan.new(
  template,
  manifest.variables,
  destination_path: File.expand_path(File.join(__dir__, '..')),
  overwrite: false
)

plan.devise
plan.execute

command_name = manifest.variables.get('command_name').value

next_steps = <<~TEXT
  ✔ Command created

  TODO:

  Add the following to cli.rb within AppArchetype::CLI:

  ```
  desc '#{command_name.underscore}', 'TODO: description'

  def #{command_name.underscore}
    cmd =  AppArchetype::Commands::#{command_name.camelize}.new(options)
    cmd.run
  end
  ```
TEXT

puts next_steps
