#!/usr/bin/env ruby

require_relative '../lib/app_archetype'

puts 'CREATE NEW COMMAND'

manifest = AppArchetype.render_template(
  collection_dir: File.join(__dir__, 'generators'),
  template_name: 'command',
  destination_path: File.expand_path(File.join(__dir__, '..'))
)

command_name = manifest.variables.get('command_name').value

next_steps = <<~TEXT
  ✔ Command created

  TODO:

  Add the following to cli.rb within AppArchetype::CLI:

  ```
  desc '#{command_name.snake_case}', 'TODO: description'

  def #{command_name.snake_case}
    cmd =  AppArchetype::Commands::#{command_name.camel_case}.new(options)
    cmd.run
  end
  ```
TEXT

puts next_steps
