#!/usr/bin/env ruby

require 'thor'

require 'app_archetype'
require 'app_archetype/cli'
require 'active_support/all'

puts 'CREATE NEW COMMAND'

template_dir = File.join(__dir__, 'generators')
manager = AppArchetype::TemplateManager.new(template_dir)
manager.load

manifest = manager.find_by_name('command')
template = manifest.template
template.load

command = AppArchetype::Commands::RenderTemplate.new(
  manager,
  File.expand_path(File.join(__dir__, '..'))
)

command.render_template(manifest, template)
command_name = manifest.variables.get('command_name').value

next_steps = <<~TEXT
  ✔ Command created

  TODO:

  Add the following to cli.rb within AppArchetype::CLI:

  ```
  desc '#{command_name.underscore}', 'TODO: description'

  def #{command_name.underscore}
    cmd =  AppArchetype::Commands::#{command_name.camelize}.new(options)
    cmd.run
  end
  ```
TEXT

puts next_steps
